name: CI/CD

on:
  release:
    types: [published]

jobs:
  deploy:
    steps:
      - name: Modrinth Release
        uses: dsx137/modrinth-release-action@main
        env:
            MODRINTH_TOKEN: xxx
        with:
            name: xxx
            project_id: puTJzCb0
            loaders: forge, fabric
            game_versions: 1.20.1, 1.20.2
            version_number: 1.1.0
            files: |
                ./build/libs/*-all.jar
      - name: Curseforge Release
        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
        with:
          api-token: "<YOUR TOKEN>"
          project-id: "1234"
          modpack-path: "./modpack.zip"
          modpack-server-path: "./modpack-server.zip" # Optional
          changelog: "Added new features" # Optional
          changelog-format: "text" # Optional
          game-version: "1.16.5" # Optional
          display-name: "My Awesome Modpack"
          server-display-name: "My Awesome Modpack Server" # Optional
          release-type: "beta"
      - name: Successful Deployed
        if: success()
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "deployed"
      - name: Failed Deployed
        if: success()
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "failed"
